### ISSUE TITLE
 how can I get the clicked position on the timeline corresponding time?

### ISSUE THREAD

**Issue by cuijiudai** [kristw/d3kit-timeline#11]

**Comment by kristw** [comment]
There is no direct way now. Have to do something along the line of getting x position then revert value from the scale. You can get scale from the chart and hack it back.

```
const scale = chart.options().scale;
const value = scale.invert(position);
```

**Comment by cuijiudai** [comment]
so I have to add click event to the timeline element to get the position first ， I had done it 。

**Comment by kristw** [comment]
Does the approach above work for you? You may have to also subtract `margin.top` or `margin.left` from position, depending on the timeline direction.

**Comment by cuijiudai** [comment]
That works . thanks !

**Comment by kristw** [comment]
Awesome. I will close this issue then.
