### ISSUE TITLE
Multiline label

### ISSUE THREAD

**Issue by GeoffreyEstrade** [kristw/d3kit-timeline#12]
Hi,
I'm new in web development. This library is wonderful and I've a lot of questions. So, how can I do a multiline label text? Not a wrap text, I need to set line1=blabla, line two=bloblo.

Tanks a lot,

**Comment by kristw** [comment]
Hi Geoffrey,

Currently, there is not a direct way to specify multi-line labels. This library uses svg `<text>`, which is unfortunately only single line. To have multiple `<text>` element for your multi-line labels. You may have to do it more manually by modifying from labella.js examples 

http://twitter.github.io/labella.js/with_text.html
http://twitter.github.io/labella.js/with_text2.html

-Krist

**Comment by GeoffreyEstrade** [comment]
Hi Kristw,
if I understand, I will have more flexibility if I do a timeline from scratch using labella.js.

I tried to redo the example but it seems to be a mistake with d3.js.
I included it with `<script type="text/javascript" src="/bower_components/d3/d3.min.js"></script>`.

bower.json looks like:
`{
    "name": "asp.net",
    "private": true,
  "dependencies": {
    "labella": "1.1.2"
  },
  "devDependencies": {
    "d3": "4.2.6"
  }
}`

There are some errors with :
- `var colorScale = d3.scale.category10();` - **Unable to get property 'category10' of undefined or null reference**
- `var timeScale = d3.time.scale()` - **Unable to get property 'scale' of undefined or null reference**

Thanks for your help.
Geoffrey

**Comment by kristw** [comment]
Please downgrade d3 to 3.5.17 or follow the [migration guide](https://github.com/d3/d3/blob/master/CHANGES.md) from d3 v3 to v4.

**Comment by GeoffreyEstrade** [comment]
Hey Kristw,
I tried to update the code for v4 but I don't understand everything. Nevermind it works with v3.5.17.
If you have time for updating examples with the last version of d3, I am interested.  ;)

Thanks again for your help and this library,
Geoffrey

**Comment by kristw** [comment]
Cool. Will put that on the to-do list. Glad it helps.
