### ISSUE TITLE
How to make interactive labels?

### ISSUE THREAD

**Issue by KhanMaytok** [kristw/d3kit-timeline#2]
Hi to everyone. 

How can the label be interactive. For example, execute a function when I click on a label

**Comment by kristw** [comment]
Thanks for the question.

``` javascript
var chart = new d3Kit.Timeline('#timeline', {...});
chart.on('labelClick', function(d,i){
  // do whatever you wish
  // d is the data associated with the clicked label, i is index
});
```

Please see API reference of [.on()](https://github.com/kristw/d3kit-timeline/blob/master/docs/api.md#on) for full list of available events.
