### ISSUE TITLE
Overflow not handled well

### ISSUE THREAD

**Issue by R-WebsterNoble** [kristw/d3kit-timeline#23]
When I change the demo code and clump a bunch of entry times together this pushes some of the labels off the bottom:

```
const data = [
    { time: new Date(1977, 4, 25), episode: 4, name: "A New Hope" },
    { time: new Date(2015, 11, 18), episode: 7, name: "The Force Awakens" },
    { time: new Date(2015, 11, 18), episode: 7, name: "The Force Awakens" },
    { time: new Date(2015, 11, 18), episode: 7, name: "The Force Awakens" },
    { time: new Date(2015, 11, 18), episode: 7, name: "The Force Awakens" },
    { time: new Date(2015, 11, 18), episode: 7, name: "The Force Awakens" },
    { time: new Date(2015, 11, 18), episode: 7, name: "The Force Awakens" }
];
```
Result:
![image](https://user-images.githubusercontent.com/16836459/188152651-0dc507c0-e24f-48de-b645-cb2b27011b9a.png)

Is there any way to avoid this happening?

Ideally I'd like it to look something like this (courtesy of my amazing paint skills):
![image](https://user-images.githubusercontent.com/16836459/188155631-902a6325-7acb-48ae-bf39-b6182fd241a6.png)

Is this possible?

**Comment by kristw** [comment]
You can set `maxPos`.

```js
var chart = new d3KitTimeline('#timeline', {
  direction: 'right',
  initialWidth: 400,
  initialHeight: 250,
  labella: { maxPos: 250 }
});
```

**Comment by R-WebsterNoble** [comment]
Thanks :)
