### ISSUE TITLE
allow non-time/Date based data

### ISSUE THREAD

**Issue by timelyportfolio** [kristw/d3kit-timeline#3]
Fantastic work with this and labella!  I know that the purpose of this is clearly to communicate date time, so please disregard if out of scope.  Could the `scale` be exposed in `options` so we could use `d3.scale.linear` instead of `d3.time.scale`?  Based on my cursory reading of the code, it seems this [line](https://github.com/kristw/d3kit-timeline/blob/master/src/d3kit-timeline.js#L72) could accept this option, and everything would work.  As an example, consider the use case presented for the `htmlwidget` wrapper of communicating time of goal in a soccer game where the scale would be 0 to about 90.

**Comment by timelyportfolio** [comment]
I tested locally adding `DEFAULT_OPTIONS = {...,scale: d3.time.scale()}` and then setting `timeScale = options.scale`, and it worked.

Regardless of whether you like this idea, would adding a `domain` option be acceptable for customization?

**Comment by kristw** [comment]
Sounds good. I like the idea to add `scale` and `domain` to options. Will try to get some spare time to take care of this.

**Comment by timelyportfolio** [comment]
I can submit a pull with what I have if you would like.  Just a couple lines.  You can see it here https://github.com/timelyportfolio/timelineR/blob/master/inst/htmlwidgets/lib/d3kit-timeline/dist/d3kit-timeline.js.

**Comment by kristw** [comment]
Done! Version bumped to 0.2.0 
I also update the documentation and add another example to http://kristw.github.io/d3kit-timeline/

**Comment by kristw** [comment]
Thanks again for your suggestions!
