### ISSUE TITLE
Rendering in hidden div

### ISSUE THREAD

**Issue by fmsolbakken** [kristw/d3kit-timeline#4]
When rendering the timeline in a div that is hidden on creation the labels overlap, and are not formatted when unhidden. Any way to fix this?

**Comment by fmsolbakken** [comment]
Solved it; if I call the chart.data([...]) after unhiding the div, the timeline renders perfectly.

Thank you for a very nice timeline!

**Comment by kristw** [comment]
Cool. Or if you did not change the data, you can also call `chart.visualize()` to render after unhiding the div.
