### ISSUE TITLE
Skeleton missing functionnality

### ISSUE THREAD

**Issue by lpwisniewski** [kristw/d3kit-timeline#5]
I'm using your lib since few weeks it fits clearly with my exceptations, but i had to add an access to skeleton's nodes to update automatically height of chart like there http://twitter.github.io/labella.js/ when you add nodes. In horizontalTimeline.js, you can see the line that fits the height automatically:
`skeleton.height(height + options.margin.top + options.margin.bottom);
`
and this thing is impossible to do with your lib at the moment.
I thought to add skeleton all free or juste add
`var nodes = skeleton.nodes;
`
at the begining.

**Comment by kristw** [comment]
Fix in version 1.1.0. I have added `.resizeToFit()` so you can call `chart.resizeToFit()` to set either the width or height automatically.

**Comment by lpwisniewski** [comment]
Thank you for adding this functionality !
