### ISSUE TITLE
feature request: font weight and other styles

### ISSUE THREAD

**Issue by simon1tan** [kristw/d3kit-timeline#9]
It would be great if we can make certain labels bold, underlined, etc.

**Comment by kristw** [comment]
Added option `textStyle` in version 1.3.0. 

Now you can customize label text like this

``` javascript
var options = {
  textStyle: {
    'fill': '#fff',
    'text-decoration' : function(d){ return d.team==='BRA'? 'none': 'underline'},
    'font-weight': function(d){ return d.team==='BRA'? 700: 400}
  }
};
```

Please see [API Reference](https://github.com/kristw/d3kit-timeline/blob/master/docs/api.md) and example 6 on
http://kristw.github.io/d3kit-timeline/
